### ISSUE TITLE
После установки vESR система застревает на загрузке

### ISSUE THREAD

**Issue by voron5096** [alekho/EVE-NG_vESR#1]
![image](https://github.com/user-attachments/assets/eb2d54a4-95c1-4bff-826a-2594f55aa1d7)

**Comment by alekho** [comment]
Инструкция написана для системы eve-ng, и системы виртуализации proxmox. Вы используете VirtualBox, советую вам ознакомиться с информацией производителя https://docs.eltex-co.ru/pages/viewpage.action?pageId=370606098

**Comment by voron5096** [comment]
> Инструкция написана для системы eve-ng, и системы виртуализации proxmox. Вы используете VirtualBox, советую вам ознакомиться с информацией производителя https://docs.eltex-co.ru/pages/viewpage.action?pageId=370606098

Если я правильно понимаю инструкцию, то установка выполняется в Proxmox. Хотелось бы найти инструкцию для среды PNET. Возможно там требуются другие шаги.

**Comment by alekho** [comment]
> > Инструкция написана для системы eve-ng, и системы виртуализации proxmox. Вы используете VirtualBox, советую вам ознакомиться с информацией производителя https://docs.eltex-co.ru/pages/viewpage.action?pageId=370606098
> 
> Если я правильно понимаю инструкцию, то установка выполняется в Proxmox. Хотелось бы найти инструкцию для среды PNET. Возможно там требуются другие шаги.

Не совсем так, в proxmox выполняется лишь подготовительная часть по созданию необходимого образа. Советую вам разобраться в механизме запуска нод в eve. Так как pnet, это форк. Думаю шаги там похожие.

**Comment by voron5096** [comment]
> в proxmox выполняется лишь подготовительная часть по созданию необходимого образа.

Можно ли обойтись без него и загрузить готовый образ сразу в EVE (PNET)? Так как в любом случае установка vESR будет выполняться уже в среде EVE (PNET). Я сделал по инструкции 

https://github.com/alekho/EVE-NG_vESR?tab=readme-ov-file#%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%B0%D0%B2%D0%BB%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC-%D0%BE%D0%B1%D1%80%D0%B0%D0%B7-%D0%B2-eve

Но к сожалению образ не появился в выборе template. Либо я что-то не понимаю, либо в pnet конфигурация настраивается как-то по другому.

**Comment by alekho** [comment]
> > в proxmox выполняется лишь подготовительная часть по созданию необходимого образа.
> 
> Можно ли обойтись без него и загрузить готовый образ сразу в EVE (PNET)? Так как в любом случае установка vESR будет выполняться уже в среде EVE (PNET). Я сделал по инструкции 
> 
> https://github.com/alekho/EVE-NG_vESR?tab=readme-ov-file#%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%B0%D0%B2%D0%BB%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC-%D0%BE%D0%B1%D1%80%D0%B0%D0%B7-%D0%B2-eve
> 
> Но к сожалению образ не появился в выборе template. Либо я что-то не понимаю, либо в pnet конфигурация настраивается как-то по другому.

Это выполнялось? https://github.com/alekho/EVE-NG_vESR?tab=readme-ov-file#%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%B0%D0%B2%D0%BB%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD
